language: php

php: 7.3

services:
  - mysql

mysql:
  database: testing
  username: root
  encoding: utf8

before_script:
  - mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction

script: composer test